version: "3"

services:
  api:
    build:
      context: "./api"
      dockerfile: "api.dockerfile"
    container_name: fastapi-api
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "always"
    depends_on:
    - postgres_final
    
  postgres_final:
    build: 
      context: "./postgres_final"
      dockerfile: "postgres_final.dockerfile"
    container_name: postgres_final
    ports:
      - '5432:5432'
    volumes:
      - sql-final-data:/var/lib/postgres/pgdata
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: abc123

  mongo_raw:
    build:
      context: "./mongo_raw"
      dockerfile: "mongo_raw.dockerfile"
    container_name: mongo_raw
    ports:
      - 27018:27017
    volumes:
      - mongo-raw-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: abc123

  ingestor:
    build:
      context: "./ingestor"
      dockerfile: "ingestor.dockerfile"
    container_name: ingestor_to_raw
    restart: "always"
    depends_on:
    - mongo_raw

  spark:
    build:
      context: "./spark"
      dockerfile: "spark.dockerfile"
    container_name: spark
    restart: "no"
    depends_on:
    - mongo_raw
volumes:
  sql-final-data:
  mongo-raw-data:

