# https://taskfile.dev

version: '3'

tasks:
    default:
      cmds:
    # list of Commands 
        - echo "run api"

    # Commands
    run:api:
        cmds:
            - "uvicorn api.main:app"
        silent: true